// Sprites em pixel art copiados do próprio jogo (spriteRows/palette do HTML).
export const PALETTE: Record<string, string> = {"r": "#c74a36", "d": "#713d26", "s": "#ffcb92", "k": "#202c36", "o": "#244f7d", "y": "#fff09d", "g": "#d4f8ad", "t": "#ecbc56", "w": "#fff5da"};

export const SPRITES: Record<string, string[]> = {
 "stand": [
  "....rrrrrr......",
  "...rrrrrrrrrr...",
  "...dddssks......",
  "..dsdsssksss....",
  "..dsddsssks.....",
  "...dssskkkk.....",
  "....ssssss......",
  "...rrorro.......",
  "..rrroorrrr.....",
  ".rrrroooorrrr...",
  ".ssroysyorrss...",
  ".sssoooooosss...",
  "....ooooooo.....",
  "...oooo.oooo....",
  "..dddd...dddd...",
  ".ddddd...ddddd.."
 ],
 "run": [
  "....rrrrrr......",
  "...rrrrrrrrrr...",
  "...dddssks......",
  "..dsdsssksss....",
  "..dsddsssks.....",
  "...dssskkkk.....",
  "....ssssss......",
  "...rroorro......",
  "..rrrooorrrss...",
  ".srrroyyorrsss..",
  ".sssoooooo......",
  "....ooooooo.....",
  "...oooo.oo......",
  "..dddd..oodd....",
  ".ddddd...ddd....",
  "..........ddd..."
 ],
 "jump": [
  "....rrrrrr......",
  "...rrrrrrrrrr...",
  "...dddssks......",
  "..dsdsssksss....",
  "..dsddsssks.....",
  "...dssskkkk.....",
  "....ssssss..ss..",
  "...rroorro.sss..",
  "..rrrooorrrss...",
  ".srrroyyorr.....",
  ".sssoooooo......",
  "...oooooooo.....",
  "..oooo..oodd....",
  ".dddd....ddd....",
  ".dddd...........",
  "................"
 ],
 "goomba": [
  ".....dddddd.....",
  "...dddddddddd...",
  "..dddddddddddd..",
  ".ddwdddddwwdddd.",
  ".ddkwdddkwddddd.",
  "dddkwwwwkwdddddd",
  "ddddkkkkdddddddd",
  "ddssssssssssdddd",
  ".ssssssssssssss.",
  "..ssssssssssss..",
  "...ddddddddd....",
  "..kkkk..kkkk....",
  ".kkkkk..kkkkk..."
 ],
 "mushroom": [
  ".....rrrrrr.....",
  "...rrrrwwrrrr...",
  "..rrrwwwwwwrrr..",
  ".rrrrwwwwwwrrrr.",
  "rrwwrrrrrrrrwwrr",
  "rwwwwrrrrrrwwwwr",
  "rwwwwrrrrrrwwwwr",
  "rrrrrrrrrrrrrrrr",
  "..ssssssssssss..",
  "...ssskskssss...",
  "...ssssssssss...",
  "....ssssssss...."
 ],
 "koopa": [
  ".....gggg.......",
  "....gggggg......",
  "....gwkwgg......",
  "....ggggggss....",
  "...ggggggsss....",
  "...gggggggg.....",
  "..ggddddddgg....",
  ".ggddddddddgg...",
  ".gddggddggddg...",
  "ggddggddggddgg..",
  "ggddddddddddgg..",
  ".gddddddddddg...",
  "..gddddddddg....",
  "...ssssssss.....",
  "..ssss..ssss....",
  "..dddd..dddd...."
 ]
};
